.PHONY: build check check
build:
	cargo build

.PHONY: run
run:
	cargo run

.PHONY: check
check:
	cargo check

.PHONY: clean
clean:
	cargo clean

.PHONY: install
install:
	cargo install

.PHONY: publish
publish:
	cargo publish --allow-dirty 

.PHONY: pkglist
pkglist:
	cargo package --list

.PHONY: login
login:
	cargo login

